version: '3'

services:
  db:
    image: postgres:14
    container_name: recuruit-postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./postgresql/script:/docker-entrypoint-initdb.d # この行を追加しただけ
    environment:
      - POSTGRES_PASSWORD=passward

  proxy:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - web

  web:
    build: .
    tty: true
    volumes:
      - "./go:/app"

volumes:
  -  db-store:
