version: '3'

services:
  db:
    image: postgres:14
    container_name: recuruit-postgres
    ports:
      - 5432:5432
    volumes:
      - db-store:/var/lib/postgresql/data
      - ./postgresql/script:/docker-entrypoint-initdb.d
    environment:
      - POSTGRES_PASSWORD=passward

  proxy:
    build: ./nginx
    ports:
      - 8080:80
    depends_on:
      - app

  app:
    build: ./app
    tty: true
    ports:
      - 9000:9000

volumes:
  db-store:
